services:
  redis:
    image: redis:7-alpine
    container_name: redis-servertech
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - servertech-net
    restart: unless-stopped

volumes:
  redis-data:

networks:
  servertech-net: {}
