// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_meta.proto
// Protobuf C++ Version: 6.30.2

#ifndef rpc_5fmeta_2eproto_2epb_2eh
#define rpc_5fmeta_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rpc_5fmeta_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_5fmeta_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_rpc_5fmeta_2eproto;
}  // extern "C"
namespace rpc {
class RpcMeta;
struct RpcMetaDefaultTypeInternal;
extern RpcMetaDefaultTypeInternal _RpcMeta_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RpcMeta_class_data_;
}  // namespace rpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace rpc {

// ===================================================================


// -------------------------------------------------------------------

class RpcMeta final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rpc.RpcMeta) */ {
 public:
  inline RpcMeta() : RpcMeta(nullptr) {}
  ~RpcMeta() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RpcMeta* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RpcMeta));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RpcMeta(::google::protobuf::internal::ConstantInitialized);

  inline RpcMeta(const RpcMeta& from) : RpcMeta(nullptr, from) {}
  inline RpcMeta(RpcMeta&& from) noexcept
      : RpcMeta(nullptr, std::move(from)) {}
  inline RpcMeta& operator=(const RpcMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcMeta& operator=(RpcMeta&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RpcMeta& default_instance() {
    return *reinterpret_cast<const RpcMeta*>(
        &_RpcMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RpcMeta& a, RpcMeta& b) { a.Swap(&b); }
  inline void Swap(RpcMeta* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcMeta* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RpcMeta* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RpcMeta>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RpcMeta& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RpcMeta& from) { RpcMeta::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RpcMeta* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "rpc.RpcMeta"; }

 protected:
  explicit RpcMeta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RpcMeta(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RpcMeta& from);
  RpcMeta(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RpcMeta&& from) noexcept
      : RpcMeta(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServiceIdFieldNumber = 1,
    kMethodIdFieldNumber = 2,
    kDataSizeFieldNumber = 3,
  };
  // string service_id = 1;
  void clear_service_id() ;
  const std::string& service_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_service_id(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_service_id();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_service_id();
  void set_allocated_service_id(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_service_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_service_id(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_service_id();

  public:
  // string method_id = 2;
  void clear_method_id() ;
  const std::string& method_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_method_id(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_method_id();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_method_id();
  void set_allocated_method_id(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_method_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_method_id(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_method_id();

  public:
  // int32 data_size = 3;
  void clear_data_size() ;
  ::int32_t data_size() const;
  void set_data_size(::int32_t value);

  private:
  ::int32_t _internal_data_size() const;
  void _internal_set_data_size(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:rpc.RpcMeta)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RpcMeta& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr service_id_;
    ::google::protobuf::internal::ArenaStringPtr method_id_;
    ::int32_t data_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fmeta_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RpcMeta_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RpcMeta

// string service_id = 1;
inline void RpcMeta::clear_service_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RpcMeta::service_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rpc.RpcMeta.service_id)
  return _internal_service_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RpcMeta::set_service_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.service_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rpc.RpcMeta.service_id)
}
inline std::string* PROTOBUF_NONNULL RpcMeta::mutable_service_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_service_id();
  // @@protoc_insertion_point(field_mutable:rpc.RpcMeta.service_id)
  return _s;
}
inline const std::string& RpcMeta::_internal_service_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.service_id_.Get();
}
inline void RpcMeta::_internal_set_service_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.service_id_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RpcMeta::_internal_mutable_service_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.service_id_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RpcMeta::release_service_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rpc.RpcMeta.service_id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.service_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.service_id_.Set("", GetArena());
  }
  return released;
}
inline void RpcMeta::set_allocated_service_id(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.service_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.service_id_.IsDefault()) {
    _impl_.service_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.RpcMeta.service_id)
}

// string method_id = 2;
inline void RpcMeta::clear_method_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RpcMeta::method_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rpc.RpcMeta.method_id)
  return _internal_method_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RpcMeta::set_method_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.method_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rpc.RpcMeta.method_id)
}
inline std::string* PROTOBUF_NONNULL RpcMeta::mutable_method_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_method_id();
  // @@protoc_insertion_point(field_mutable:rpc.RpcMeta.method_id)
  return _s;
}
inline const std::string& RpcMeta::_internal_method_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_id_.Get();
}
inline void RpcMeta::_internal_set_method_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.method_id_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RpcMeta::_internal_mutable_method_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.method_id_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RpcMeta::release_method_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rpc.RpcMeta.method_id)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.method_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.method_id_.Set("", GetArena());
  }
  return released;
}
inline void RpcMeta::set_allocated_method_id(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.method_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.method_id_.IsDefault()) {
    _impl_.method_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:rpc.RpcMeta.method_id)
}

// int32 data_size = 3;
inline void RpcMeta::clear_data_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_size_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t RpcMeta::data_size() const {
  // @@protoc_insertion_point(field_get:rpc.RpcMeta.data_size)
  return _internal_data_size();
}
inline void RpcMeta::set_data_size(::int32_t value) {
  _internal_set_data_size(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:rpc.RpcMeta.data_size)
}
inline ::int32_t RpcMeta::_internal_data_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_size_;
}
inline void RpcMeta::_internal_set_data_size(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_size_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // rpc_5fmeta_2eproto_2epb_2eh
