services:
  web-back-gpp:
    image: server-chat-backend:20251215-ssh-clangd-v2
    container_name: web-back-gpp
    working_dir: /workspace
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ../../:/workspace
    networks:
      - servertech-net
    ports:
      - "2222:22"
      - "8080:8080"
    command: >
      bash -lc "
      set -e;
      /usr/sbin/sshd -t;
      /usr/sbin/sshd;
      exec sleep infinity
      "
networks:
  servertech-net: {}
