// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_demo.proto
// Protobuf C++ Version: 6.30.2

#ifndef rpc_5fdemo_2eproto_2epb_2eh
#define rpc_5fdemo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/service.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rpc_5fdemo_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_5fdemo_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_rpc_5fdemo_2eproto;
}  // extern "C"
class RPCRequest;
struct RPCRequestDefaultTypeInternal;
extern RPCRequestDefaultTypeInternal _RPCRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPCRequest_class_data_;
class RPCResponse;
struct RPCResponseDefaultTypeInternal;
extern RPCResponseDefaultTypeInternal _RPCResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPCResponse_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class RPCResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RPCResponse) */ {
 public:
  inline RPCResponse() : RPCResponse(nullptr) {}
  ~RPCResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPCResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPCResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPCResponse(::google::protobuf::internal::ConstantInitialized);

  inline RPCResponse(const RPCResponse& from) : RPCResponse(nullptr, from) {}
  inline RPCResponse(RPCResponse&& from) noexcept
      : RPCResponse(nullptr, std::move(from)) {}
  inline RPCResponse& operator=(const RPCResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPCResponse& operator=(RPCResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPCResponse& default_instance() {
    return *reinterpret_cast<const RPCResponse*>(
        &_RPCResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RPCResponse& a, RPCResponse& b) { a.Swap(&b); }
  inline void Swap(RPCResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPCResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPCResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPCResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPCResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPCResponse& from) { RPCResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPCResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RPCResponse"; }

 protected:
  explicit RPCResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPCResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPCResponse& from);
  RPCResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPCResponse&& from) noexcept
      : RPCResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSerialNumberFieldNumber = 1,
  };
  // string serial_number = 1;
  void clear_serial_number() ;
  const std::string& serial_number() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_serial_number(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_serial_number();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_serial_number();
  void set_allocated_serial_number(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_serial_number() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_serial_number(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_serial_number();

  public:
  // @@protoc_insertion_point(class_scope:RPCResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 33,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPCResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr serial_number_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fdemo_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPCResponse_class_data_;
// -------------------------------------------------------------------

class RPCRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RPCRequest) */ {
 public:
  inline RPCRequest() : RPCRequest(nullptr) {}
  ~RPCRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPCRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPCRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPCRequest(::google::protobuf::internal::ConstantInitialized);

  inline RPCRequest(const RPCRequest& from) : RPCRequest(nullptr, from) {}
  inline RPCRequest(RPCRequest&& from) noexcept
      : RPCRequest(nullptr, std::move(from)) {}
  inline RPCRequest& operator=(const RPCRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPCRequest& operator=(RPCRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPCRequest& default_instance() {
    return *reinterpret_cast<const RPCRequest*>(
        &_RPCRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RPCRequest& a, RPCRequest& b) { a.Swap(&b); }
  inline void Swap(RPCRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPCRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPCRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPCRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPCRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPCRequest& from) { RPCRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPCRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RPCRequest"; }

 protected:
  explicit RPCRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPCRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPCRequest& from);
  RPCRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPCRequest&& from) noexcept
      : RPCRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientNameFieldNumber = 1,
  };
  // string client_name = 1;
  void clear_client_name() ;
  const std::string& client_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_client_name(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_client_name();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_client_name();
  void set_allocated_client_name(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_client_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_client_name(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_client_name();

  public:
  // @@protoc_insertion_point(class_scope:RPCRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 30,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPCRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr client_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fdemo_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPCRequest_class_data_;

// ===================================================================


// -------------------------------------------------------------------

class DemoService_Stub;
class DemoService : public ::google::protobuf::Service {
 protected:
  DemoService() = default;

 public:
  using Stub = DemoService_Stub;

  DemoService(const DemoService&) = delete;
  DemoService& operator=(const DemoService&) = delete;
  virtual ~DemoService() = default;

  static const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL descriptor();

  virtual void GetSerialNumber(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                        const ::RPCRequest* PROTOBUF_NONNULL request,
                        ::RPCResponse* PROTOBUF_NONNULL response,
                        ::google::protobuf::Closure* PROTOBUF_NULLABLE done);
  virtual void GetAnotherSerialNumber(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                        const ::RPCRequest* PROTOBUF_NONNULL request,
                        ::RPCResponse* PROTOBUF_NONNULL response,
                        ::google::protobuf::Closure* PROTOBUF_NULLABLE done);

  // implements Service ----------------------------------------------
  const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL GetDescriptor() override;

  void CallMethod(
      const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method,
      ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
      const ::google::protobuf::Message* PROTOBUF_NONNULL request,
      ::google::protobuf::Message* PROTOBUF_NONNULL response,
      ::google::protobuf::Closure* PROTOBUF_NULLABLE done) override;

  const ::google::protobuf::Message& GetRequestPrototype(
      const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const override;

  const ::google::protobuf::Message& GetResponsePrototype(
      const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const override;
};

class DemoService_Stub final : public DemoService {
 public:
  DemoService_Stub(::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel);
  DemoService_Stub(::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);

  DemoService_Stub(const DemoService_Stub&) = delete;
  DemoService_Stub& operator=(const DemoService_Stub&) = delete;

  ~DemoService_Stub() override;

  inline ::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel() { return channel_; }

  // implements DemoService ------------------------------------------
  void GetSerialNumber(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                        const ::RPCRequest* PROTOBUF_NONNULL request,
                        ::RPCResponse* PROTOBUF_NONNULL response,
                        ::google::protobuf::Closure* PROTOBUF_NULLABLE done) override;
  void GetAnotherSerialNumber(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                        const ::RPCRequest* PROTOBUF_NONNULL request,
                        ::RPCResponse* PROTOBUF_NONNULL response,
                        ::google::protobuf::Closure* PROTOBUF_NULLABLE done) override;

 private:
  ::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel_;
  bool owns_channel_;
};
// ===================================================================



// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RPCRequest

// string client_name = 1;
inline void RPCRequest::clear_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RPCRequest::client_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RPCRequest.client_name)
  return _internal_client_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPCRequest::set_client_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.client_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RPCRequest.client_name)
}
inline std::string* PROTOBUF_NONNULL RPCRequest::mutable_client_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_client_name();
  // @@protoc_insertion_point(field_mutable:RPCRequest.client_name)
  return _s;
}
inline const std::string& RPCRequest::_internal_client_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_name_.Get();
}
inline void RPCRequest::_internal_set_client_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.client_name_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RPCRequest::_internal_mutable_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.client_name_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RPCRequest::release_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RPCRequest.client_name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.client_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.client_name_.Set("", GetArena());
  }
  return released;
}
inline void RPCRequest::set_allocated_client_name(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.client_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.client_name_.IsDefault()) {
    _impl_.client_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RPCRequest.client_name)
}

// -------------------------------------------------------------------

// RPCResponse

// string serial_number = 1;
inline void RPCResponse::clear_serial_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serial_number_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RPCResponse::serial_number() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RPCResponse.serial_number)
  return _internal_serial_number();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPCResponse::set_serial_number(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.serial_number_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RPCResponse.serial_number)
}
inline std::string* PROTOBUF_NONNULL RPCResponse::mutable_serial_number()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_serial_number();
  // @@protoc_insertion_point(field_mutable:RPCResponse.serial_number)
  return _s;
}
inline const std::string& RPCResponse::_internal_serial_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.serial_number_.Get();
}
inline void RPCResponse::_internal_set_serial_number(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.serial_number_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL RPCResponse::_internal_mutable_serial_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.serial_number_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE RPCResponse::release_serial_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RPCResponse.serial_number)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.serial_number_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.serial_number_.Set("", GetArena());
  }
  return released;
}
inline void RPCResponse::set_allocated_serial_number(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.serial_number_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.serial_number_.IsDefault()) {
    _impl_.serial_number_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RPCResponse.serial_number)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // rpc_5fdemo_2eproto_2epb_2eh
