// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_demo.proto
// Protobuf C++ Version: 6.30.2

#include "rpc_demo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr RPCResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        serial_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RPCResponse::RPCResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPCResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RPCResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPCResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPCResponseDefaultTypeInternal() {}
  union {
    RPCResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPCResponseDefaultTypeInternal _RPCResponse_default_instance_;

inline constexpr RPCRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        client_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RPCRequest::RPCRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPCRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RPCRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPCRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPCRequestDefaultTypeInternal() {}
  union {
    RPCRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPCRequestDefaultTypeInternal _RPCRequest_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_rpc_5fdemo_2eproto = nullptr;
static const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL
    file_level_service_descriptors_rpc_5fdemo_2eproto[1];
const ::uint32_t
    TableStruct_rpc_5fdemo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::RPCRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::RPCRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::RPCRequest, _impl_.client_name_),
        0,
        PROTOBUF_FIELD_OFFSET(::RPCResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::RPCResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::RPCResponse, _impl_.serial_number_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::RPCRequest)},
        {10, 19, -1, sizeof(::RPCResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_RPCRequest_default_instance_._instance,
    &::_RPCResponse_default_instance_._instance,
};
const char descriptor_table_protodef_rpc_5fdemo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016rpc_demo.proto\"!\n\nRPCRequest\022\023\n\013client"
    "_name\030\001 \001(\t\"$\n\013RPCResponse\022\025\n\rserial_num"
    "ber\030\001 \001(\t2p\n\013DemoService\022,\n\017GetSerialNum"
    "ber\022\013.RPCRequest\032\014.RPCResponse\0223\n\026GetAno"
    "therSerialNumber\022\013.RPCRequest\032\014.RPCRespo"
    "nseB\003\200\001\001b\006proto3"
};
static ::absl::once_flag descriptor_table_rpc_5fdemo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_5fdemo_2eproto = {
    false,
    false,
    216,
    descriptor_table_protodef_rpc_5fdemo_2eproto,
    "rpc_demo.proto",
    &descriptor_table_rpc_5fdemo_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_rpc_5fdemo_2eproto::offsets,
    file_level_enum_descriptors_rpc_5fdemo_2eproto,
    file_level_service_descriptors_rpc_5fdemo_2eproto,
};
// ===================================================================

class RPCRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RPCRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPCRequest, _impl_._has_bits_);
};

RPCRequest::RPCRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPCRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RPCRequest)
}
PROTOBUF_NDEBUG_INLINE RPCRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::RPCRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        client_name_(arena, from.client_name_) {}

RPCRequest::RPCRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPCRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPCRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPCRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RPCRequest)
}
PROTOBUF_NDEBUG_INLINE RPCRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        client_name_(arena) {}

inline void RPCRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RPCRequest::~RPCRequest() {
  // @@protoc_insertion_point(destructor:RPCRequest)
  SharedDtor(*this);
}
inline void RPCRequest::SharedDtor(MessageLite& self) {
  RPCRequest& this_ = static_cast<RPCRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.client_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPCRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPCRequest(arena);
}
constexpr auto RPCRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPCRequest),
                                            alignof(RPCRequest));
}
constexpr auto RPCRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPCRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RPCRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPCRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPCRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPCRequest>(), &RPCRequest::ByteSizeLong,
              &RPCRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPCRequest, _impl_._cached_size_),
          false,
      },
      &RPCRequest::kDescriptorMethods,
      &descriptor_table_rpc_5fdemo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPCRequest_class_data_ =
        RPCRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL RPCRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPCRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPCRequest_class_data_.tc_table);
  return RPCRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2>
RPCRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPCRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPCRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RPCRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string client_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RPCRequest, _impl_.client_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_name = 1;
    {PROTOBUF_FIELD_OFFSET(RPCRequest, _impl_.client_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\12\13\0\0\0\0\0\0"
    "RPCRequest"
    "client_name"
  }},
};
PROTOBUF_NOINLINE void RPCRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:RPCRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.client_name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPCRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPCRequest& this_ = static_cast<const RPCRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPCRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPCRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:RPCRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string client_name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_client_name().empty()) {
      const std::string& _s = this_._internal_client_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RPCRequest.client_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RPCRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPCRequest::ByteSizeLong(const MessageLite& base) {
  const RPCRequest& this_ = static_cast<const RPCRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPCRequest::ByteSizeLong() const {
  const RPCRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:RPCRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string client_name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_client_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_client_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPCRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RPCRequest*>(&to_msg);
  auto& from = static_cast<const RPCRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RPCRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_client_name().empty()) {
      _this->_internal_set_client_name(from._internal_client_name());
    } else {
      if (_this->_impl_.client_name_.IsDefault()) {
        _this->_internal_set_client_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RPCRequest::CopyFrom(const RPCRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RPCRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPCRequest::InternalSwap(RPCRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_name_, &other->_impl_.client_name_, arena);
}

::google::protobuf::Metadata RPCRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPCResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RPCResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPCResponse, _impl_._has_bits_);
};

RPCResponse::RPCResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPCResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RPCResponse)
}
PROTOBUF_NDEBUG_INLINE RPCResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::RPCResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        serial_number_(arena, from.serial_number_) {}

RPCResponse::RPCResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPCResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPCResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPCResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RPCResponse)
}
PROTOBUF_NDEBUG_INLINE RPCResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        serial_number_(arena) {}

inline void RPCResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RPCResponse::~RPCResponse() {
  // @@protoc_insertion_point(destructor:RPCResponse)
  SharedDtor(*this);
}
inline void RPCResponse::SharedDtor(MessageLite& self) {
  RPCResponse& this_ = static_cast<RPCResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.serial_number_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPCResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPCResponse(arena);
}
constexpr auto RPCResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPCResponse),
                                            alignof(RPCResponse));
}
constexpr auto RPCResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPCResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RPCResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPCResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPCResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPCResponse>(), &RPCResponse::ByteSizeLong,
              &RPCResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPCResponse, _impl_._cached_size_),
          false,
      },
      &RPCResponse::kDescriptorMethods,
      &descriptor_table_rpc_5fdemo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPCResponse_class_data_ =
        RPCResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL RPCResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPCResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPCResponse_class_data_.tc_table);
  return RPCResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2>
RPCResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPCResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPCResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RPCResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string serial_number = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RPCResponse, _impl_.serial_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string serial_number = 1;
    {PROTOBUF_FIELD_OFFSET(RPCResponse, _impl_.serial_number_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\15\0\0\0\0\0\0"
    "RPCResponse"
    "serial_number"
  }},
};
PROTOBUF_NOINLINE void RPCResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:RPCResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.serial_number_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPCResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPCResponse& this_ = static_cast<const RPCResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPCResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPCResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:RPCResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string serial_number = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_serial_number().empty()) {
      const std::string& _s = this_._internal_serial_number();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RPCResponse.serial_number");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RPCResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPCResponse::ByteSizeLong(const MessageLite& base) {
  const RPCResponse& this_ = static_cast<const RPCResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPCResponse::ByteSizeLong() const {
  const RPCResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:RPCResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string serial_number = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_serial_number().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_serial_number());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPCResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RPCResponse*>(&to_msg);
  auto& from = static_cast<const RPCResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RPCResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_serial_number().empty()) {
      _this->_internal_set_serial_number(from._internal_serial_number());
    } else {
      if (_this->_impl_.serial_number_.IsDefault()) {
        _this->_internal_set_serial_number("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RPCResponse::CopyFrom(const RPCResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RPCResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPCResponse::InternalSwap(RPCResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.serial_number_, &other->_impl_.serial_number_, arena);
}

::google::protobuf::Metadata RPCResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL DemoService::descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rpc_5fdemo_2eproto);
  return file_level_service_descriptors_rpc_5fdemo_2eproto[0];
}

const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL DemoService::GetDescriptor() {
  return descriptor();
}

void DemoService::GetSerialNumber(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                         const ::RPCRequest* PROTOBUF_NONNULL,
                         ::RPCResponse* PROTOBUF_NONNULL,
                         ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  controller->SetFailed("Method GetSerialNumber() not implemented.");
  done->Run();
}
void DemoService::GetAnotherSerialNumber(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                         const ::RPCRequest* PROTOBUF_NONNULL,
                         ::RPCResponse* PROTOBUF_NONNULL,
                         ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  controller->SetFailed("Method GetAnotherSerialNumber() not implemented.");
  done->Run();
}

void DemoService::CallMethod(
    const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method,
    ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
    const ::google::protobuf::Message* PROTOBUF_NONNULL request,
    ::google::protobuf::Message* PROTOBUF_NONNULL response, ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  ABSL_DCHECK_EQ(method->service(), file_level_service_descriptors_rpc_5fdemo_2eproto[0]);
  switch (method->index()) {
    case 0:
      this->GetSerialNumber(controller, ::google::protobuf::DownCastMessage<::RPCRequest>(request),
                   ::google::protobuf::DownCastMessage<::RPCResponse>(response), done);
      break;
    case 1:
      this->GetAnotherSerialNumber(controller, ::google::protobuf::DownCastMessage<::RPCRequest>(request),
                   ::google::protobuf::DownCastMessage<::RPCResponse>(response), done);
      break;

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& DemoService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::RPCRequest::default_instance();
    case 1:
      return ::RPCRequest::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()->GetPrototype(
          method->input_type());
  }
}

const ::google::protobuf::Message& DemoService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::RPCResponse::default_instance();
    case 1:
      return ::RPCResponse::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()->GetPrototype(
          method->output_type());
  }
}

DemoService_Stub::DemoService_Stub(::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel)
    : channel_(channel), owns_channel_(false) {}

DemoService_Stub::DemoService_Stub(
    ::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
    : channel_(channel),
      owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}

DemoService_Stub::~DemoService_Stub() {
  if (owns_channel_) delete channel_;
}

void DemoService_Stub::GetSerialNumber(
    ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
    const ::RPCRequest* PROTOBUF_NONNULL request, ::RPCResponse* PROTOBUF_NONNULL response,
    ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  channel_->CallMethod(descriptor()->method(0), controller,
                       request, response, done);
}
void DemoService_Stub::GetAnotherSerialNumber(
    ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
    const ::RPCRequest* PROTOBUF_NONNULL request, ::RPCResponse* PROTOBUF_NONNULL response,
    ::google::protobuf::Closure* PROTOBUF_NULLABLE done) {
  channel_->CallMethod(descriptor()->method(1), controller,
                       request, response, done);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_5fdemo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
